name: flutter_image_filters
description: Image filters based on OpenGL(SPIR-V) fragment shaders with useful preview widgets
version: 0.0.32
homepage: https://github.com/nikolaydymura/flutter_image_filters
repository: https://github.com/nikolaydymura/flutter_image_filters
platforms:
  android:
  ios:
  macos:
  web:

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.7.0"

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  flutter_gpu_filters_interface: ^0.0.18
  exif: ^3.3.0
  build: ^3.0.0
  source_gen: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  image: ^4.5.4
  analyzer: ^7.7.1

flutter:

  assets:
    - assets/empty_texture.jpg

  shaders:
    - shaders/brightness.frag
    - shaders/bulge_distortion.frag
    - shaders/cga_colorspace.frag
    - shaders/color_invert.frag
    - shaders/color_matrix.frag
    - shaders/contrast.frag
    - shaders/crosshatch.frag
    - shaders/exposure.frag
    - shaders/false_color.frag
    - shaders/gamma.frag
    - shaders/glass_sphere.frag
    - shaders/grayscale.frag
    - shaders/hald_lookup.frag
    - shaders/halftone.frag
    - shaders/haze.frag
    - shaders/highlight_shadow.frag
    - shaders/hue.frag
#    - shaders/kuwahara.frag
    - shaders/lookup.frag
    - shaders/luminance.frag
    - shaders/luminance_threshold.frag
    - shaders/monochrome.frag
    - shaders/none.frag
    - shaders/opacity.frag
    - shaders/pixelation.frag
    - shaders/posterize.frag
    - shaders/rgb.frag
    - shaders/saturation.frag
    - shaders/solarize.frag
    - shaders/swirl.frag
    - shaders/vibrance.frag
    - shaders/vignette.frag
    - shaders/white_balance.frag
    - shaders/zoom_blur.frag
